### ISSUE TITLE
UbiquityMyAdminBaseController contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by Nyrtub** [phpMv/ubiquity-webtools#6]
[Sun Feb 13 19:20:23 2022] PHP 7.4.27 Development Server (http://192.168.1.160:8090) started
[Sun Feb 13 19:20:34 2022] 192.168.1.98:37340 Accepted
[Sun Feb 13 19:20:34 2022] PHP Fatal error:  Class Ubiquity\controllers\admin\UbiquityMyAdminBaseController contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Ubiquity\controllers\admin\UbiquityMyAdminBaseController::showSimpleMessage, Ubiquity\controllers\admin\UbiquityMyAdminBaseController::showConfMessage) in /var/www/cms/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php on line 80
[Sun Feb 13 19:20:34 2022] 192.168.1.98:37340 Closing

**Comment by jcheron** [comment]
Hi @Nyrtub 
Can you specify the context?
Versions used of php, devtools, Ubiquity

On a blank project, without doing anything?

**Comment by Nyrtub** [comment]
Right
Just create a blank project, without doing anything.

> 148  cd  /var/www/
> 149  Ubiquity new cms -a --themes=bootstrap,semantic
> 150  cd cms/
> 151  Ubiquity serve -h 192.168.1.160

> Ubiquity version
> 
>     · PHP 7.4.27
>     · Ubiquity devtools (1.2.13)

**Comment by jcheron** [comment]
Can you run `Ubiquity version`in your project root?
Thanks!

**Comment by Nyrtub** [comment]
> JB@serveur-hp:/var/www$ cd /var/www/cms/public && Ubiquity version
> 
>     · The project folder is /var/www/cms
> PHP Fatal error:  Access level to Ubiquity\controllers\admin\traits\ConfigTrait::showConfMessage() must be public (as in class Ubiquity\controllers\admin\traits\ModelsTrait) in /var/www/cms/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php on line 34

> JB@serveur-hp:/var/www/cms/public$ cd /var/www/cms/public && Ubiquity serve -h=192.168.1.160 
> 
>     · The project folder is /var/www/cms
> 
>     · Starting php server at 192.168.1.160:8090...
>     · Press Ctrl+C to stop it!
> 
> [Mon Feb 14 19:46:53 2022] PHP 7.4.27 Development Server (http://192.168.1.160:8090) started
> [Mon Feb 14 19:47:07 2022] 192.168.1.78:44372 Accepted
> [Mon Feb 14 19:47:07 2022] PHP Fatal error:  Access level to Ubiquity\controllers\admin\traits\ConfigTrait::showConfMessage() must be public (as in class Ubiquity\controllers\admin\traits\ModelsTrait) in /var/www/cms/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php on line 34
> [Mon Feb 14 19:47:07 2022] 192.168.1.78:44372 Closing
> [Mon Feb 14 19:47:07 2022] 192.168.1.78:44374 Accepted
> [Mon Feb 14 19:47:07 2022] 192.168.1.78:44374 Closing

> JB@serveur-hp:/var/www/cms/public$ cd /var/www/cms/ && Ubiquity version
> 
>     · The project folder is /var/www/cms
> PHP Fatal error:  Access level to Ubiquity\controllers\admin\traits\ConfigTrait::showConfMessage() must be public (as in class Ubiquity\controllers\admin\traits\ModelsTrait) in /var/www/cms/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php on line 34

> JB@serveur-hp:/var/www/cms$ cd /var/www/cms/ && Ubiquity serve -h=192.168.1.160 
> 
>     · The project folder is /var/www/cms
> 
>     · Starting php server at 192.168.1.160:8090...
>     · Press Ctrl+C to stop it!
> 
> [Mon Feb 14 19:49:10 2022] PHP 7.4.27 Development Server (http://192.168.1.160:8090) started
> [Mon Feb 14 19:49:14 2022] 192.168.1.78:44410 Accepted
> [Mon Feb 14 19:49:14 2022] PHP Fatal error:  Access level to Ubiquity\controllers\admin\traits\ConfigTrait::showConfMessage() must be public (as in class Ubiquity\controllers\admin\traits\ModelsTrait) in /var/www/cms/vendor/phpmv/ubiquity-webtools/src/Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php on line 34
> [Mon Feb 14 19:49:14 2022] 192.168.1.78:44410 Closing
> [Mon Feb 14 19:49:14 2022] 192.168.1.78:44412 Accepted
> [Mon Feb 14 19:49:14 2022] 192.168.1.78:44412 Closing
>

**Comment by jcheron** [comment]
The version of the `devtools` used does not seem compatible with the project. The `1.2.13` is from July 2020...
The current version is 1.3.10.
If you want to update it :
```bash
composer global update
```
And as the project was created with this old version, I think it should be recreated...

**Comment by Nyrtub** [comment]
Yes. All right.
I close this issue and continue to use it...

Many thanks.
